[package]
name = "zj-quit"
version = "0.4.0"
authors = ["Cristian Dominguez", "lkonga"]
edition = "2021"
description = "Zellij plugin for confirming quit session, close pane, and close tab actions"

[dependencies]
zellij-tile = "0.42.2"

[profile.release]
opt-level = "s"
lto = true
